#!/bin/bash
# This is example cofiguration of llama-server, for more https://github.com/ggml-org/llama.cpp

#llama-server \
#	-m ~/.llamaorch/models/example-model.gguf \
#	-ngl 28 \
#	-c 6144 \
#	-t 6 \
#	-b 192 \
#	--ubatch-size 64 \
#	--flash-attn off \
#	--cont-batching \
#	--port 18080 \
#	--host 0.0.0.0
